version: '3'
services:
  goweb:
    container_name: 'goserviceJenkinsDocker'
    build: '.'
    ports:
      - '8080:8080'
    volumes:
      - './goserviceJenkinsDocker:/go/src/goserviceJenkinsDocker'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'